### ISSUE TITLE
ACF Options page endpoint

### ISSUE THREAD

**Issue by ryanstroh** [factor1/better-rest-endpoints#20]
Hey

Great plugin. I was wondering if there was a way to access Advanced custom fields through an endpoint or if there is anything in the pipeline to expose this.

E.g better-rest-endpoints/v1/options/{options-page-slug}

**Comment by mattada** [comment]
HEy @ryanstroh thanks! yes you can fully access the ACF fields via the end point. Both on page and options page fields. 

@erwstout can you remind us which path to pull there?

**Comment by erwstout** [comment]
So as of right now ACF values are available through each post/page/cpt endpoint. There is not a direct endpoint to ACF options or things like that. I'm sure it could be easily added but I don't know how much time I'll be able to devote to this plugin at this point. It may be up to @mattada @mlpatt23 to get this worked in or @ryanstroh feel free to submit a PR.
