### ISSUE TITLE
Undefined variable $bre_page in get_page_by_id.php

### ISSUE THREAD

**Issue by struct78** [factor1/better-rest-endpoints#21]
When I attempt to hit an endpoint for a page (e.g. `/wp-json/better-rest-endpoints/v1/page/3`) that is in **draft** mode, I get the following error:

```
Notice: Undefined variable: bre_page in web/app/plugins/better-rest-endpoints/includes/get_page_by_id.php on line 103
```

This is because you've defined the $bre_page variable inside the while() loop, and are trying to access it in the conditional.

```
  if( $query->have_posts() ){
    while( $query->have_posts() ) {
      ...

      $bre_page = new stdClass();
    
      ....

  }  else {
      return $bre_page;  // <-- This guy
  }
```

**Comment by erwstout** [comment]
Hi @struct78 - good catch. I'm not sure how soon I'll be able to get to this as I'm not actively working on WP anymore, but maybe the fine folks at @factor1/staff can help, or feel free to submit a PR and if it looks good I'll merge it.

**Comment by erwstout** [comment]
This should be fixed soon, planning on doing a quick pass on all the open issues and updating the plugin.
